version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tmc_frontend
    ports:
      - "80:80"
    networks:
      - tmc_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tmc_backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    networks:
      - tmc_network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: tmc_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tmc_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: tmc_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - tmc_network
    restart: unless-stopped

networks:
  tmc_network:
    driver: bridge

volumes:
  postgres_data:
